from fpdf import FPDF
from datetime import datetime
import io
from .graph import get_graph_service

class PDFReport(FPDF):
    def header(self):
        # Logo placeholder
        self.set_font('helvetica', 'B', 15)
        self.set_text_color(31, 41, 55) # Gray-800
        self.cell(0, 10, 'DiggerAI - Solution Report', border=False, align='L')
        self.ln(10)
        self.set_draw_color(229, 231, 235) # Gray-200
        self.line(self.get_x(), self.get_y(), self.get_x() + 190, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(107, 114, 128) # Gray-500
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Antigravity AI | {datetime.now().strftime("%Y-%m-%d %H:%M")}', align='C')

class ReportService:
    def __init__(self, supabase_client):
        self.supabase = supabase_client
        self.graph_service = get_graph_service()

    def _safe_str(self, s):
        if s is None: return ""
        # Basic cleanup to avoid characters that Helvetica can't handle if they aren't Latin-1
        try:
            return str(s).encode('latin-1', 'replace').decode('latin-1')
        except:
            return str(s)

    def generate_solution_report(self, solution_id: str) -> bytes:
        print(f"[REPORT SERVICE] Starting report generation for solution: {solution_id}")
        # 1. Fetch Solution Info
        solution_res = self.supabase.table("solutions").select("*").eq("id", solution_id).execute()
        if not solution_res.data:
            raise Exception(f"Solution {solution_id} not found")
        
        solution = solution_res.data[0]
        
        # 2. Fetch Graph Data
        print(f"[REPORT SERVICE] Fetching graph data...")
        graph_data = self.graph_service.get_graph_data(solution_id)
        nodes = graph_data.get("nodes", [])
        edges = graph_data.get("edges", [])
        print(f"[REPORT SERVICE] Found {len(nodes)} nodes and {len(edges)} edges")
        
        # 3. Process Data for Report
        stats = {
            "total_nodes": len(nodes),
            "total_edges": len(edges),
            "by_type": {}
        }
        
        source_nodes = []
        sink_nodes = []
        transform_nodes = []
        
        for n in nodes:
            ntype = n["data"].get("type", "UNKNOWN").upper()
            stats["by_type"][ntype] = stats["by_type"].get(ntype, 0) + 1
            
            if ntype == "SOURCE": source_nodes.append(n)
            elif ntype == "SINK": sink_nodes.append(n)
            elif ntype == "TRANSFORM": transform_nodes.append(n)

        # 4. Build PDF
        print(f"[REPORT SERVICE] Building PDF document...")
        pdf = PDFReport()
        pdf.add_page()
        
        # Title Section
        pdf.set_font('helvetica', 'B', 24)
        pdf.set_text_color(17, 24, 39) # Gray-900
        pdf.cell(0, 20, self._safe_str(solution.get("name", "Unnamed Solution")), ln=True)
        
        pdf.set_font('helvetica', '', 10)
        pdf.set_text_color(75, 85, 99) # Gray-600
        pdf.cell(0, 6, self._safe_str(f"Solution ID: {solution_id}"), ln=True)
        pdf.cell(0, 6, self._safe_str(f"Project Path: {solution.get('file_path', 'N/A')}"), ln=True)
        pdf.ln(10)

        # Executive Summary
        pdf.set_font('helvetica', 'B', 14)
        pdf.set_text_color(31, 41, 55)
        pdf.cell(0, 10, "Executive Summary", ln=True)
        
        pdf.set_font('helvetica', '', 11)
        pdf.set_text_color(55, 65, 81)
        summary_text = (
            f"This graph contains {stats['total_nodes']} interactive components and {stats['total_edges']} data flow connections. "
            f"The discovery process identified {len(source_nodes)} sources, {len(sink_nodes)} destinations, "
            f"and {len(transform_nodes)} logic transformation blocks."
        )
        pdf.multi_cell(0, 7, self._safe_str(summary_text))
        pdf.ln(10)

        # Stats Table
        pdf.set_font('helvetica', 'B', 12)
        pdf.cell(0, 10, "Component Distribution", ln=True)
        
        pdf.set_fill_color(249, 250, 251) # Gray-50
        pdf.set_font('helvetica', 'B', 10)
        pdf.cell(95, 10, "Component Type", border=1, fill=True)
        pdf.cell(95, 10, "Count", border=1, fill=True, ln=True)
        
        pdf.set_font('helvetica', '', 10)
        for ntype, count in sorted(stats["by_type"].items()):
            pdf.cell(95, 10, ntype, border=1)
            pdf.cell(95, 10, str(count), border=1, ln=True)
        pdf.ln(10)

        # Asset Inventory Section
        pdf.add_page()
        pdf.set_font('helvetica', 'B', 14)
        pdf.cell(0, 10, "Asset Inventory", ln=True)
        pdf.set_font('helvetica', '', 10)
        pdf.multi_cell(0, 6, "Below is the detailed list of all discovered components, grouped by their type.")
        pdf.ln(5)

        for ntype in sorted(stats["by_type"].keys()):
            type_nodes = [n for n in nodes if n["data"].get("type", "").upper() == ntype]
            if not type_nodes: continue

            pdf.set_font('helvetica', 'B', 12)
            pdf.set_text_color(37, 99, 235) # Blue-600
            pdf.cell(0, 10, f"{ntype} ({len(type_nodes)})", ln=True)
            pdf.set_text_color(55, 65, 81)
            
            pdf.set_font('helvetica', 'B', 9)
            pdf.set_fill_color(229, 231, 235) # Gray-200 for header
            pdf.cell(100, 8, "Name", border=1, fill=True)
            pdf.cell(90, 8, "Schema / System", border=1, fill=True, ln=True)
            
            pdf.set_font('helvetica', '', 9)
            row_count = 0
            for tn in sorted(type_nodes, key=lambda x: x["data"].get("label", "")):
                label = tn["data"].get("label", "N/A")
                schema = tn["data"].get("schema") or tn["data"].get("system") or "N/A"
                columns = tn["data"].get("columns", [])
                
                # Zebra striping
                fill = row_count % 2 == 1
                if fill:
                    pdf.set_fill_color(249, 250, 251) # Gray-50
                
                # Truncate long labels
                if len(label) > 60: label = label[:57] + "..."
                
                pdf.cell(100, 8, self._safe_str(label), border='LR', fill=fill)
                pdf.cell(90, 8, self._safe_str(schema), border='LR', fill=fill, ln=True)
                
                # Add columns if they exist (indented)
                if columns:
                    pdf.set_font('helvetica', 'I', 8)
                    pdf.set_text_color(107, 114, 128)
                    col_str = "Columns: " + ", ".join(columns[:20]) # Limit to 20
                    if len(columns) > 20: col_str += f" ... (+{len(columns)-20} more)"
                    pdf.multi_cell(0, 6, self._safe_str("    " + col_str), border='LR', fill=fill)
                    pdf.set_font('helvetica', '', 9)
                    pdf.set_text_color(55, 65, 81)
                
                # Bottom border for the last element of the group or every row to close it
                pdf.cell(190, 0, '', border='T', ln=True)
                row_count += 1
                
            pdf.ln(5)

        # Transformations Section
        if transform_nodes:
            pdf.add_page()
            pdf.set_font('helvetica', 'B', 16)
            pdf.set_text_color(17, 24, 39)
            pdf.cell(0, 12, "Logic Transformation Catalog", ln=True)
            pdf.set_font('helvetica', '', 11)
            pdf.set_text_color(75, 85, 99)
            pdf.multi_cell(0, 7, "The following logical transformations were successfully extracted from the pipeline nodes.")
            pdf.ln(8)

            for tn in transform_nodes:
                tags = tn["data"].get("tags", {})
                logic = tags.get("transformations", []) or []
                if not logic: continue

                # Header for the node
                pdf.set_font('helvetica', 'B', 12)
                pdf.set_fill_color(243, 244, 246) # Gray-100
                pdf.set_text_color(31, 41, 55)
                
                # Page break check
                if pdf.get_y() > 230: pdf.add_page()
                
                pdf.cell(0, 10, f" Source Node: {tn['data'].get('label', tn['id'])}", border=1, ln=True, fill=True)
                
                for item in logic:
                    col = item.get("column", "N/A")
                    expr = item.get("expression", "N/A")
                    
                    # Ensure room for the expression block
                    if pdf.get_y() > 250: pdf.add_page()
                    
                    pdf.set_font('helvetica', 'B', 10)
                    pdf.set_text_color(37, 99, 235)
                    pdf.cell(0, 8, f" Target Column: {col}", border='LR', ln=True)
                    
                    # Expression box
                    pdf.set_font('courier', '', 9)
                    pdf.set_text_color(31, 41, 55)
                    pdf.set_fill_color(255, 255, 255)
                    # We use a multi_cell for the expression
                    current_y = pdf.get_y()
                    pdf.multi_cell(0, 5, self._safe_str(expr), border='LRB')
                    pdf.ln(4)
                
                pdf.ln(6)

        print(f"[REPORT SERVICE] PDF generation complete. Returning bytes.")
        return bytes(pdf.output())
